### ISSUE TITLE
Bulletpoints in Admin Screens

### ISSUE THREAD

**Issue by tporteus** [NHSLeadership/nhsblocks#125]
![Screenshot 2023-06-21 at 17 34 40](https://github.com/NHSLeadership/nhsblocks/assets/1842033/e77f144d-ed8b-44e1-acb3-5a084a2c65e5)

Since  1.3.6 activating the plugin causes additional styling in WP-Admin.

I think the following rules in the CSS are overly wide.

.nhsuk-list, ol, ul {
    font-size: 16px;
    font-size: 1rem;
    line-height: 1.5;
    list-style-type: none;
    margin-bottom: 16px;
    margin-top: 0;
    padding-left:0
}

@media (min-width: 40.0625em) {
    .nhsuk-list, ol, ul {
        font-size: 19px;
        font-size: 1.1875rem;
        line-height:1.47368
    }
}

@media print {
    .nhsuk-list, ol, ul {
        font-size: 14pt;
        line-height:1.15
    }
}

@media (min-width: 40.0625em) {
    .nhsuk-list, ol, ul {
        margin-bottom:24px
    }
}

**Comment by maheshmuralip** [comment]
Thanks @tporteus 
v1.3.7 hopefully will fix this.
