### ISSUE TITLE
Issue with simple reveals since new update

### ISSUE THREAD

**Issue by ShanayaKR** [NHSLeadership/nhsblocks#136]
Hello, I updated NHS Blocks on our website yesterday and was happy to see that we can now add lists and links inside them using the inline HTML option!

However, since updating we have had a new issue. To recreate:

1. create a Simple Reveal block (either type, it happens with both) and enter some text into it
2. update the page
3. view the page (leaving the editor)
4. go back to the editor 

When you look inside the reveal after the steps above, it appears empty and you can't edit the current contents. You can only go to the page, copy what you had in it before, and re-paste it in. Or use the 'edit as HTML' option to update the text, as the contents still show there, just not in visual mode.

Hope that makes sense. Previously when we have had issues with blocks it has been caused by the Nightingale Companion (see the issue I just added on that github repo) plugin, but it still does this with the Companion plugin deactivated. If any further information is required, please let me know!

**Comment by maheshmuralip** [comment]
Thanks @ShanayaKR 
We will look into this.

**Comment by tporteus** [comment]
We are seeing this issue also.

**Comment by maheshmuralip** [comment]
This is fixed in v1.3.10.
Reverted one previous commit, and we will be working to support html content in simple reveal. 
Many thanks.
