### ISSUE TITLE
Stripes block layout in editor overlaps containing div

### ISSUE THREAD

**Issue by Johntyb** [NHSLeadership/nhsblocks#53]
Stripes block: http://prntscr.com/tkk2dw Very difficult to use and configure correctly.

**Comment by tblacker7** [comment]
Will be fixed on next release. https://github.com/NHSLeadership/nightingale-2-0/commit/e4b66d1ec000e41529553ce04bb992bb6433e21b < also fixed in main theme library (if both theme and plugin are active, it only pulls styling from theme to save duplication)
