### ISSUE TITLE
Card Region Missing Top Border

### ISSUE THREAD

**Issue by tporteus** [NHSLeadership/nhsblocks#73]
![Screenshot 2020-12-03 at 17 18 37](https://user-images.githubusercontent.com/1842033/101064280-b8145a80-358b-11eb-9679-6f8221c1e35b.png)

**Comment by tblacker7** [comment]
![Screenshot 2021-01-29 at 17 15 16](https://user-images.githubusercontent.com/44897304/106306172-936bf480-6255-11eb-8013-2961b05f3986.png)
Thank you for highlighting this - somewhere along the line we added a 1px grey line to the box, which isn't correct at all. This will be rectified in next release.
