### ISSUE TITLE
Deprecated filter: block_categories 

### ISSUE THREAD

**Issue by bobbingwide** [NHSLeadership/nhsblocks#87]
Getting the following message in the block editor

<b>Deprecated</b>:  block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in <b>C:\apache\htdocs\wp-a2z\wp-includes\functions.php</b> on line <b>5586</b><br />

### Proposed fix 
Change nhsblock.php as suggested by the deprecated message.
```
/**
 * Add custom "nhsblocks" block category.
 *
 * @link https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#managing-block-categories
 */
add_filter( 'block_categories_all', 'nhsblocks_block_categories', 10, 2 );
```

**Comment by maheshmuralip** [comment]
Hi @bobbingwide,

This is fixed in v1.3.10.
Many thanks.
