### ISSUE TITLE
Accessibility issues on Simple Reveal

### ISSUE THREAD

**Issue by ShanayaKR** [NHSLeadership/nhsblocks#89]
Hi, the NHS Simple Reveal block flags up an important accessibility issue - duplicate IDs. Each one created has the following div: 
`<div class="nhsuk-details__text" id="details-content-" aria-hidden="true">...</div>`
meaning that if I have more than 1 reveal on the page, it becomes non-accessible

**Comment by maheshmuralip** [comment]
@ShanayaKR A fix is added in the version 1.3.9
Thanks
