### ISSUE TITLE
Simple reveal doesn't allow customisation within

### ISSUE THREAD

**Issue by ShanayaKR** [NHSLeadership/nhsblocks#90]
Looking at the NHS Design Manual for both [details](https://service-manual.nhs.uk/design-system/components/details) and [expanders](https://service-manual.nhs.uk/design-system/components/expander), you should be able to put a html list inside either of them. This doesn't seem to be possible using the nhs-block from what I have experienced

**Comment by maheshmuralip** [comment]
@ShanayaKR A fix is added in the version 1.3.9
Thanks
